backend:
  name: git-gateway
  repo: annelikripsaar/workwalks
  branch: dev

media_folder: static/assets
public_folder: /assets

collections:
  - name: projects
    label: Project
    folder: projects
    create: true
    slug: "{{slug}}"
    fields:
      - { name: title, label: Title }
      - { name: author, label: Author }
      - { name: body, label: "English description", widget: markdown }
      - { name: est, label: "Estonian description", widget: markdown }
      - { name: ru, label: "Russian description", widget: markdown }
      - {
          name: galleryImages,
          label: "Gallery images",
          widget: list,
          summary: "{{fields.image}}",
          field: { name: image, label: Image, widget: image },
          required: false,
        }
